/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    testimonios: Testimonio;
    'clientes-trabajados': ClientesTrabajado;
    programas: Programa;
    'team-members': TeamMember;
    faq: Faq;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonios: TestimoniosSelect<false> | TestimoniosSelect<true>;
    'clientes-trabajados': ClientesTrabajadosSelect<false> | ClientesTrabajadosSelect<true>;
    programas: ProgramasSelect<false> | ProgramasSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'programas-hub': ProgramasHub;
    'taller-seo-con-ia': TallerSeoConIa;
    'quienes-somos': QuienesSomo;
    'testimonios-page': TestimoniosPage;
    reto: Reto;
    home: Home;
    diplomado: Diplomado;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'programas-hub': ProgramasHubSelect<false> | ProgramasHubSelect<true>;
    'taller-seo-con-ia': TallerSeoConIaSelect<false> | TallerSeoConIaSelect<true>;
    'quienes-somos': QuienesSomosSelect<false> | QuienesSomosSelect<true>;
    'testimonios-page': TestimoniosPageSelect<false> | TestimoniosPageSelect<true>;
    reto: RetoSelect<false> | RetoSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    diplomado: DiplomadoSelect<false> | DiplomadoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios".
 */
export interface Testimonio {
  id: number;
  nombre: string;
  rol?: string | null;
  ubicacion?: string | null;
  quote: string;
  foto?: (number | null) | Media;
  featuredOnHome?: boolean | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes-trabajados".
 */
export interface ClientesTrabajado {
  id: number;
  nombre: string;
  logo: number | Media;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas".
 */
export interface Programa {
  id: number;
  slug: string;
  badge: string;
  nombre: string;
  descripcion: string;
  precio: string;
  precioNota?: string | null;
  ctaLabel: string;
  ctaHref: string;
  orden?: number | null;
  menuDesc?: string | null;
  menuBadge?: string | null;
  testimonios?: (number | Testimonio)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  nombre: string;
  rol: string;
  bio: string;
  foto?: (number | null) | Media;
  iniciales: string;
  web?: string | null;
  mostrarEnQuienesSomos?: boolean | null;
  mostrarEnDiplomado?: boolean | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  page: 'home' | 'diplomado' | 'reto' | 'taller-seo-con-ia';
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'programas';
      value: number | Programa;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonios';
        value: number | Testimonio;
      } | null)
    | ({
        relationTo: 'clientes-trabajados';
        value: number | ClientesTrabajado;
      } | null)
    | ({
        relationTo: 'programas';
        value: number | Programa;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios_select".
 */
export interface TestimoniosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  ubicacion?: T;
  quote?: T;
  foto?: T;
  featuredOnHome?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes-trabajados_select".
 */
export interface ClientesTrabajadosSelect<T extends boolean = true> {
  nombre?: T;
  logo?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas_select".
 */
export interface ProgramasSelect<T extends boolean = true> {
  slug?: T;
  badge?: T;
  nombre?: T;
  descripcion?: T;
  precio?: T;
  precioNota?: T;
  ctaLabel?: T;
  ctaHref?: T;
  orden?: T;
  menuDesc?: T;
  menuBadge?: T;
  testimonios?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  bio?: T;
  foto?: T;
  iniciales?: T;
  web?: T;
  mostrarEnQuienesSomos?: T;
  mostrarEnDiplomado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  page?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  navbar: {
    siteNav: {
      label: string;
      href: string;
      type: 'route' | 'anchor';
      id?: string | null;
    }[];
    siteCta: {
      label: string;
      href: string;
    };
    programMenu: {
      label: string;
      href: string;
      desc: string;
      badge: string;
      id?: string | null;
    }[];
  };
  footer: {
    footerColumns: {
      title: string;
      links: {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
    footerSocials: {
      socialId: 'youtube' | 'tiktok' | 'whatsapp' | 'instagram' | 'linkedin';
      label: string;
      href: string;
      id?: string | null;
    }[];
    footerMeta: {
      blurb: string;
      copyrightLeft: string;
      copyrightRight: string;
      mobilePanelBlurb: string;
    };
  };
  seo: {
    siteUrl: string;
    orgName: string;
    orgAlternateName?: string | null;
    orgLogo?: (number | null) | Media;
    orgDescription: string;
    orgFoundingDate: string;
    founderName: string;
    founderJobTitle: string;
    sameAs: {
      url: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas-hub".
 */
export interface ProgramasHub {
  id: number;
  hero: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
  };
  ctaFinal: {
    titulo: string;
    texto: string;
    boton: {
      label: string;
      href: string;
    };
  };
  programas: (number | Programa)[];
  relatedLinks?: {
    title?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taller-seo-con-ia".
 */
export interface TallerSeoConIa {
  id: number;
  hero: {
    eyebrow: string;
    titulo: string;
    subtitulo: string;
    duracion: string;
  };
  incluye: {
    texto: string;
    valor?: string | null;
    id?: string | null;
  }[];
  paraQuien: string;
  precio: {
    monto: string;
    opciones: {
      texto: string;
      id?: string | null;
    }[];
  };
  cta: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quienes-somos".
 */
export interface QuienesSomo {
  id: number;
  hero: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
  };
  historia: {
    eyebrow: string;
    titulo: string;
    parrafos: {
      texto: string;
      id?: string | null;
    }[];
    quote: {
      texto: string;
      autor: string;
    };
  };
  fundadora: {
    eyebrow: string;
    nombre: string;
    rol: string;
    bio: {
      texto: string;
      id?: string | null;
    }[];
    foto: number | Media;
  };
  equipo?: {
    eyebrow?: string | null;
    titulo?: string | null;
    subtitulo?: string | null;
    items?: (number | TeamMember)[] | null;
  };
  metodologia: {
    eyebrow: string;
    titulo: string;
    pilares: {
      nombre: string;
      descripcion: string;
      id?: string | null;
    }[];
  };
  stats?: {
    items?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaFinal: {
    titulo: string;
    texto?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    boton: {
      label: string;
      href: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios-page".
 */
export interface TestimoniosPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
  };
  gridTitulo: string;
  logos?: {
    /**
     * Ej. "Profesionales de empresas como"
     */
    texto?: string | null;
    items?: (number | ClientesTrabajado)[] | null;
  };
  reto: {
    eyebrow: string;
    titulo: string;
    texto: string;
  };
  retoGaleria?: (number | Media)[] | null;
  cta: {
    titulo: string;
    texto?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    boton: {
      label: string;
      href: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reto".
 */
export interface Reto {
  id: number;
  urgencia: string;
  hero: {
    eyebrow: string;
    titulo: string;
    destacado: string;
    texto: string;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    precioTexto: string;
    ctas?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    imagen?: (number | null) | Media;
  };
  razonNoEscalas: {
    titulo: string;
    parrafo: string;
    frases?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  mentora: {
    nombre: string;
    rol: string;
    stats?:
      | {
          valor: string;
          etiqueta: string;
          id?: string | null;
        }[]
      | null;
    historia: string;
    quote: string;
    cierre: string;
    foto?: (number | null) | Media;
  };
  agenda?:
    | {
        dia: string;
        titulo: string;
        descripcion: string;
        imagen?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  comparacion?:
    | {
        deSiempre: string;
        elReto: string;
        id?: string | null;
      }[]
    | null;
  incluye?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  premios: {
    mayor: {
      titulo: string;
      imagen?: (number | null) | Media;
    };
    becas: {
      titulo: string;
      imagen?: (number | null) | Media;
    };
    comoSeGana: string;
  };
  pricing: {
    precio: string;
    precioNota: string;
    incluyeTexto: string;
    ctas?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    nota: string;
    whatsapp: string;
  };
  ganadoresIntro: string;
  ganadores?:
    | {
        nombre: string;
        edicion: string;
        imagen?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  faq?: (number | Faq)[] | null;
  ctaFinal: {
    titulo: string;
    botonLabel: string;
    botonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    badgeText?: string | null;
    eyebrow?: string | null;
    tituloPre?: string | null;
    tituloAccent?: string | null;
    tituloPost?: string | null;
    subtitulo?: string | null;
    texto?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    imagen?: (number | null) | Media;
    ctaPrimario: {
      label: string;
      href: string;
      id?: string | null;
    };
    ctaSecundario: {
      label: string;
      href: string;
      id?: string | null;
    };
    microcopy?: string | null;
    avatares?: (number | Media)[] | null;
    ratingTexto?: string | null;
    videoBackground?: (number | null) | Media;
  };
  problema: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    items?:
      | {
          /**
           * Nombre de icono lucide (e.g. "rocket", "target")
           */
          icon?: string | null;
          titulo: string;
          descripcion?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  beneficios: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    items?:
      | {
          /**
           * Nombre de icono lucide (e.g. "rocket", "target")
           */
          icon?: string | null;
          titulo: string;
          descripcion?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  programas: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    boton: {
      label: string;
      href: string;
      id?: string | null;
    };
    items?: (number | Programa)[] | null;
  };
  pricing: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    planes?:
      | {
          nombre: string;
          badge?: string | null;
          precio: string;
          precioTachado?: string | null;
          precioNota?: string | null;
          cuotasTexto?: string | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          cta: {
            label: string;
            href: string;
            id?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    ctaAsesoria: {
      titulo?: string | null;
      texto?: string | null;
      cta: {
        label: string;
        href: string;
        id?: string | null;
      };
    };
  };
  instructor: {
    eyebrow: string;
    nombre: string;
    rol: string;
    bioCorta1: string;
    bioCorta2: string;
    stats?: {
      items?:
        | {
            value: string;
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    foto?: (number | null) | Media;
    teaser: {
      label: string;
      href: string;
      id?: string | null;
    };
  };
  testimonios?: {
    eyebrow?: string | null;
    titulo?: string | null;
    items?: (number | Testimonio)[] | null;
  };
  logos?: {
    /**
     * Ej. "Profesionales de empresas como"
     */
    texto?: string | null;
    items?: (number | ClientesTrabajado)[] | null;
  };
  faq?: {
    eyebrow?: string | null;
    titulo?: string | null;
    items?: (number | Faq)[] | null;
  };
  ctaFinal: {
    titulo: string;
    texto?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    boton: {
      label: string;
      href: string;
      id?: string | null;
    };
  };
  stickyCta: {
    boton: {
      label: string;
      href: string;
      id?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diplomado".
 */
export interface Diplomado {
  id: number;
  hero: {
    badgeText?: string | null;
    eyebrow?: string | null;
    tituloPre?: string | null;
    tituloAccent?: string | null;
    tituloPost?: string | null;
    subtitulo?: string | null;
    texto?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    imagen?: (number | null) | Media;
    ctaPrimario: {
      label: string;
      href: string;
      id?: string | null;
    };
    ctaSecundario: {
      label: string;
      href: string;
      id?: string | null;
    };
    microcopy?: string | null;
  };
  origin: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    items?:
      | {
          /**
           * Nombre de icono lucide (e.g. "rocket", "target")
           */
          icon?: string | null;
          titulo: string;
          descripcion?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  audience: {
    titulo: string;
    subtitulo?: string | null;
    tituloPerfiles?: string | null;
    perfiles?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    tituloDudas?: string | null;
    dudas?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    notaFinal?: string | null;
  };
  /**
   * Copy propia del diplomado (EPAM). No reusar el copy de quienes-somos.metodologia.
   */
  methodology: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    items?:
      | {
          /**
           * Nombre de icono lucide (e.g. "rocket", "target")
           */
          icon?: string | null;
          titulo: string;
          descripcion?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  curriculum: {
    eyebrow?: string | null;
    titulo: string;
    semanas: {
      numero: number;
      titulo: string;
      detalle: string;
      id?: string | null;
    }[];
  };
  howItWorks: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    items?:
      | {
          /**
           * Nombre de icono lucide (e.g. "rocket", "target")
           */
          icon?: string | null;
          titulo: string;
          descripcion?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  team: {
    teamIntro: {
      eyebrow?: string | null;
      titulo: string;
      subtitulo?: string | null;
    };
    equipo?: {
      eyebrow?: string | null;
      titulo?: string | null;
      subtitulo?: string | null;
      items?: (number | TeamMember)[] | null;
    };
    mentorSection: {
      titulo: string;
      nombre: string;
      web?: string | null;
      bio: {
        texto: string;
        id?: string | null;
      }[];
      quote?: string | null;
    };
  };
  benefits: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    items?:
      | {
          texto: string;
          valor?: string | null;
          id?: string | null;
        }[]
      | null;
    extras?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  pricing: {
    titulo: string;
    subtitulo?: string | null;
    planNombre: string;
    badgeText?: string | null;
    precio: string;
    precioTachado?: string | null;
    precioNota?: string | null;
    descripcion?: string | null;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    garantiaTexto?: string | null;
  };
  faq?: {
    eyebrow?: string | null;
    titulo?: string | null;
    items?: (number | Faq)[] | null;
  };
  ctaFinal: {
    titulo: string;
    texto?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    boton: {
      label: string;
      href: string;
      id?: string | null;
    };
  };
  relatedLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  courseMeta?: {
    price?: string | null;
    /**
     * Duración ISO 8601, ej. "P16W" (16 semanas).
     */
    courseWorkload?: string | null;
    /**
     * YYYY-MM-DD. Vacío si el curso es rolling/on-demand.
     */
    startDate?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navbar?:
    | T
    | {
        siteNav?:
          | T
          | {
              label?: T;
              href?: T;
              type?: T;
              id?: T;
            };
        siteCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        programMenu?:
          | T
          | {
              label?: T;
              href?: T;
              desc?: T;
              badge?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        footerColumns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    id?: T;
                  };
              id?: T;
            };
        footerSocials?:
          | T
          | {
              socialId?: T;
              label?: T;
              href?: T;
              id?: T;
            };
        footerMeta?:
          | T
          | {
              blurb?: T;
              copyrightLeft?: T;
              copyrightRight?: T;
              mobilePanelBlurb?: T;
            };
      };
  seo?:
    | T
    | {
        siteUrl?: T;
        orgName?: T;
        orgAlternateName?: T;
        orgLogo?: T;
        orgDescription?: T;
        orgFoundingDate?: T;
        founderName?: T;
        founderJobTitle?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas-hub_select".
 */
export interface ProgramasHubSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
      };
  ctaFinal?:
    | T
    | {
        titulo?: T;
        texto?: T;
        boton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  programas?: T;
  relatedLinks?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taller-seo-con-ia_select".
 */
export interface TallerSeoConIaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        duracion?: T;
      };
  incluye?:
    | T
    | {
        texto?: T;
        valor?: T;
        id?: T;
      };
  paraQuien?: T;
  precio?:
    | T
    | {
        monto?: T;
        opciones?:
          | T
          | {
              texto?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quienes-somos_select".
 */
export interface QuienesSomosSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
      };
  historia?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        parrafos?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        quote?:
          | T
          | {
              texto?: T;
              autor?: T;
            };
      };
  fundadora?:
    | T
    | {
        eyebrow?: T;
        nombre?: T;
        rol?: T;
        bio?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        foto?: T;
      };
  equipo?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?: T;
      };
  metodologia?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        pilares?:
          | T
          | {
              nombre?: T;
              descripcion?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  ctaFinal?:
    | T
    | {
        titulo?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        boton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios-page_select".
 */
export interface TestimoniosPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
      };
  gridTitulo?: T;
  logos?:
    | T
    | {
        texto?: T;
        items?: T;
      };
  reto?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        texto?: T;
      };
  retoGaleria?: T;
  cta?:
    | T
    | {
        titulo?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        boton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reto_select".
 */
export interface RetoSelect<T extends boolean = true> {
  urgencia?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        destacado?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        precioTexto?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        imagen?: T;
      };
  razonNoEscalas?:
    | T
    | {
        titulo?: T;
        parrafo?: T;
        frases?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  mentora?:
    | T
    | {
        nombre?: T;
        rol?: T;
        stats?:
          | T
          | {
              valor?: T;
              etiqueta?: T;
              id?: T;
            };
        historia?: T;
        quote?: T;
        cierre?: T;
        foto?: T;
      };
  agenda?:
    | T
    | {
        dia?: T;
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        id?: T;
      };
  comparacion?:
    | T
    | {
        deSiempre?: T;
        elReto?: T;
        id?: T;
      };
  incluye?:
    | T
    | {
        text?: T;
        id?: T;
      };
  premios?:
    | T
    | {
        mayor?:
          | T
          | {
              titulo?: T;
              imagen?: T;
            };
        becas?:
          | T
          | {
              titulo?: T;
              imagen?: T;
            };
        comoSeGana?: T;
      };
  pricing?:
    | T
    | {
        precio?: T;
        precioNota?: T;
        incluyeTexto?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        nota?: T;
        whatsapp?: T;
      };
  ganadoresIntro?: T;
  ganadores?:
    | T
    | {
        nombre?: T;
        edicion?: T;
        imagen?: T;
        id?: T;
      };
  faq?: T;
  ctaFinal?:
    | T
    | {
        titulo?: T;
        botonLabel?: T;
        botonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badgeText?: T;
        eyebrow?: T;
        tituloPre?: T;
        tituloAccent?: T;
        tituloPost?: T;
        subtitulo?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        imagen?: T;
        ctaPrimario?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        ctaSecundario?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        microcopy?: T;
        avatares?: T;
        ratingTexto?: T;
        videoBackground?: T;
      };
  problema?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?:
          | T
          | {
              icon?: T;
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  beneficios?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?:
          | T
          | {
              icon?: T;
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  programas?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        boton?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        items?: T;
      };
  pricing?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        planes?:
          | T
          | {
              nombre?: T;
              badge?: T;
              precio?: T;
              precioTachado?: T;
              precioNota?: T;
              cuotasTexto?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        ctaAsesoria?:
          | T
          | {
              titulo?: T;
              texto?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
            };
      };
  instructor?:
    | T
    | {
        eyebrow?: T;
        nombre?: T;
        rol?: T;
        bioCorta1?: T;
        bioCorta2?: T;
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
            };
        foto?: T;
        teaser?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  testimonios?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        items?: T;
      };
  logos?:
    | T
    | {
        texto?: T;
        items?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        items?: T;
      };
  ctaFinal?:
    | T
    | {
        titulo?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        boton?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  stickyCta?:
    | T
    | {
        boton?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diplomado_select".
 */
export interface DiplomadoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badgeText?: T;
        eyebrow?: T;
        tituloPre?: T;
        tituloAccent?: T;
        tituloPost?: T;
        subtitulo?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        imagen?: T;
        ctaPrimario?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        ctaSecundario?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        microcopy?: T;
      };
  origin?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?:
          | T
          | {
              icon?: T;
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  audience?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
        tituloPerfiles?: T;
        perfiles?:
          | T
          | {
              text?: T;
              id?: T;
            };
        tituloDudas?: T;
        dudas?:
          | T
          | {
              text?: T;
              id?: T;
            };
        notaFinal?: T;
      };
  methodology?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?:
          | T
          | {
              icon?: T;
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  curriculum?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        semanas?:
          | T
          | {
              numero?: T;
              titulo?: T;
              detalle?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?:
          | T
          | {
              icon?: T;
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
      };
  team?:
    | T
    | {
        teamIntro?:
          | T
          | {
              eyebrow?: T;
              titulo?: T;
              subtitulo?: T;
            };
        equipo?:
          | T
          | {
              eyebrow?: T;
              titulo?: T;
              subtitulo?: T;
              items?: T;
            };
        mentorSection?:
          | T
          | {
              titulo?: T;
              nombre?: T;
              web?: T;
              bio?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              quote?: T;
            };
      };
  benefits?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        items?:
          | T
          | {
              texto?: T;
              valor?: T;
              id?: T;
            };
        extras?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
        planNombre?: T;
        badgeText?: T;
        precio?: T;
        precioTachado?: T;
        precioNota?: T;
        descripcion?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        garantiaTexto?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        items?: T;
      };
  ctaFinal?:
    | T
    | {
        titulo?: T;
        texto?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        boton?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  relatedLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  courseMeta?:
    | T
    | {
        price?: T;
        courseWorkload?: T;
        startDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}